<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Penny.Core\Penny.Core.csproj" />
    <ProjectReference Include="..\Penny.Security\Penny.Security.csproj" />
    <ProjectReference Include="..\Penny.Protocol\Penny.Protocol.csproj" />
    <ProjectReference Include="..\Penny.Network\Penny.Network.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Penny.Agent</RootNamespace>
    <AssemblyName>Penny.Agent</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\config\agent.settings.example.json" Link="config\agent.settings.example.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
